---
title: "SIM Project 2. Preprocessing"
author: "Adrià Casanova, Víctor Garcia, Zhengyong Ji"
date: "2023-12-02"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: no
editor_options:
  chunk_output_type: console
---

```{r, echo=T, message=FALSE, warning=FALSE, results='hide'}
# Clean the workspace
if(!is.null(dev.list())) dev.off()
rm(list = ls())
```

```{r}
# Import the libraries

library(dplyr) 
```


```{r}
# Import the dataset
df = read.csv("WA_Fn-UseC_-Telco-Customer-Churn.xls"); summary (df)
str(df)
```

# 1. Data Quality Report

```{r}
# The data has customerID and Churn, both should be removed from the trianing set for the modelling.

# The only numerical feature that we have are tenure, MonthlyCharges and TotalChages.
numeric_val = c(6, 19, 20)

# So the remaining will be categorical feature.
categoric_val = c(names(df))
# Remove the ID and target
categoric_val = categoric_val[-c(1,21,numeric_val)]

df$Churn = as.factor(df$Churn)
```

```{r}
# Transforma categoric into factor and numerical into integer.
df[categoric_val] = lapply(df[categoric_val], as.factor)

df[numeric_val] = lapply(df[numeric_val], as.numeric)
```

```{r}
# Let's check the distribution of numeric variable, in order to add discretization to convert it into facotrs.
sapply(select(df, numeric_val), table)
# The distribution of numerical variable are not normal.
hist(df$tenure)
hist(df$TotalCharges)
hist(df$MonthlyCharges)
# So we need to find a way to discretize these feature but not losing information. TO DO

# And for the factors, there is no missing values
sapply(select(df, categoric_val), table)

```

```{r}
summary(df)

# Checking the overall data quality, there is only 11 missing from TotalCharges.
df[which(is.na(df$TotalCharges)),]

# The reason that TotalCharges is NA is because the tenure is 0, meaning that the it's a fresh joined client. In this situation, instead of NA, we can convert it into 0, or more precisely compute it as product of "tenure" and "MonthlyCharges".

df$TotalCharges[which(is.na(df$TotalCharges))] = df$MonthlyCharges[which(is.na(df$TotalCharges))] * df$tenure[which(is.na(df$TotalCharges))]

# Now there is no missing values
summary(df)
```

```{r}
# We can check if there is any inconsistency in total charges.
# First, let's compute the expected total charges as product of monthly charges and tenure
expected_total_charges = df$MonthlyCharges * df$tenure

# Then plot it in a linear regression model, where we can see that there is no outliers.
plot(expected_total_charges, df$TotalCharges)
```

